### ISSUE TITLE
How different it is going to be than django-async-redis

### ISSUE THREAD

**Issue by pySilver** [amirreza8002/django-valkey#2]
Hi!

Thanks for valkey support! I'm wondering how different this package is going to be than https://github.com/Andrew-Chen-Wang/django-async-redis (giving that Valkey is supposed to be drop-in replacement)?

**Comment by amirreza8002** [comment]
hi there

[migration guide](https://django-valkey.readthedocs.io/en/latest/migration.html) should cover all you need to know
I'm trying to stay consistent with django-redis, unless something has a seriouse problem 

also note that the async client can not be used for django's cache middlewares, until they add the support for it
